version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.7.0
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      SERVICES: dynamodb, ssm, iam, sts #, lambda, apigateway, cloudwatch, logs
      LS_LOG: ${LS_LOG:-debug}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'