version: '3.7'
services:
  mongodb-standalone:
    image: mongo:7
    container_name: mongo-7-bank-account-recipient
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: sB6mbtzNHmCQI4eN4yLo