version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.7.0
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      SERVICES: dynamodb, iam, sts, lambda, apigateway, ssm, cloudwatch
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_DYNAMODB_ENDPOINT: 'http://localstack:4566'
      AWS_SSM_ENDPOINT: 'http://localstack:4566'
      AWS_DYNAMODB_RECIPIENTS_TABLE_NAME: 'recipients-dev-localstack'
      LS_LOG: ${LS_LOG:-debug}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
