aws:
  access-key-id: 'test'
  secret-key: 'test'
  region: 'us-east-1'
  dynamodb:
    endpoint: 'http://localhost:4566'
    tables:
      recipients:
        table-name: 'recipients-localstack'
  ssm:
    endpoint: 'http://localhost:4566'
    parameters:
      jwt-signature-secret:
        name: '/jwt/signature/localstack/secret'

redis:
  enabled: true
  uri:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  ssl: true
  cache:
    recipients:
      ttl-in-seconds: ${REDIS_TTL_IN_SECONDS:3600}
  pool:
    enabled: false
    max-size: 10