micronaut:
  server:
    port: 8086
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${aws.ssm.jwt-signature-secret.value}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  dynamodb:
    tables:
      recipients:
        table-name: ${AWS_DYNAMODB_RECIPIENTS_TABLE_NAME}

  ssm:
    parameters:
      jwt-signature-secret:
        name: ${AWS_SSM_JWT_SIGNATURE_SECRET_NAME}