micronaut:
  application:
    name: bank-account-recipients
  server:
    port: 8086

i18n:
  default-locale: en_US

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  dynamodb:
    table-name: ${AWS_DYNAMODB_RECIPIENTS_TABLE_NAME}
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}

jackson:
  mapper:
    accept-case-insensitive-enums: true
    accept-single-value-as-array: true

