micronaut:
  application:
    name: bank-account-recipient
  server:
    port: 8086

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  dynamodb:
    table-name: 'recipients'
    endpoint: ${AWS_DYNAMODB_ENDPOINT}

jackson:
  mapper:
    accept-case-insensitive-enums: true
    accept-single-value-as-array: true

