micronaut:
  environments:
    - dev

aws:
  access-key-id: test
  secret-key: test
  region: us-east-1
  dynamodb:
    table-name: ${AWS_DYNAMODB_RECIPIENTS_TABLE_NAME}
    endpoint: 'http://127.0.0.1:4566'

