micronaut:
  server:
    port: 8087
  openapi:
    filename: recipients-swagger-spec
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    authentication: bearer
    endpoints:
      login:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${aws.ssm.jwt-signature-secret.value}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  dynamodb:
    tables:
      recipients:
        table-name: ${AWS_DYNAMODB_RECIPIENTS_TABLE_NAME}

  ssm:
    parameters:
      jwt-signature-secret:
        name: ${AWS_SSM_JWT_SIGNATURE_SECRET_NAME}