micronaut:
  application:
    name: bank-account-recipient
  server:
    port: 8086

mongodb:
  uri: mongodb://127.0.0.1:27017/recipients
  package-names:
    - 'com.blitzar.bank_account_recipient.domain'

jackson:
  mapper:
    accept-case-insensitive-enums: true
    accept-single-value-as-array: true

