name: Build and Package

on:
  workflow_call:

jobs:
  # Phase 1: Build, run unit tests and package
  build-package:
    runs-on: ubuntu-latest

    env:
      LOCALSTACK_VERSION: "3.7.0"
      RYUK_VERSION: "0.7.0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK with Maven cache
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven

      - name: Build and Package
        run: mvn clean package --batch-mode

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bank-account-recipients
          path: target/bank-account-recipients-0.1.jar