name: Microservice CI/CD for GraalVM Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NATIVE_ZIP_NAME: "bank-account-recipients-linux-2023.zip"
      AWS_REGION: "eu-west-3"
      LINUX_2023_LAMBDA_NAME: "bank-account-recipients-linux-2023"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM for Native Image
        uses: graalvm/setup-graalvm@v2
        with:
          graalvm-version: '22.3.0'
          java-version: '17'

      # Install Native Image component
      - name: Install Native Image component
        run: |
          gu install native-image

      # Build the native image using GraalVM
      - name: Build Native Image
        run: |
          mvn package -Pnative -DskipTests

      # Package the native image as a zip file
      - name: Package Native Image as Zip
        run: |
          zip -j target/${{ env.NATIVE_ZIP_NAME }} target/bank-account-recipients-0.1-native

      # Configure AWS credentials for deployment
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Deploy the native image zip to AWS Lambda (Linux 2023 runtime)
      - name: Deploy Native Image to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LINUX_2023_LAMBDA_NAME }} \
            --zip-file fileb://target/${{ env.NATIVE_ZIP_NAME }}
