name: Microservice CI with LocalStack and Docker Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK with Maven cache
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven  # Automatically caches Maven dependencies

      # Cache LocalStack image
      - name: Cache LocalStack-3.7.0 image
        id: cache-localstack
        uses: actions/cache@v3
        with:
          path: /tmp/localstack-cache
          key: ${{ runner.os }}-localstack-3.7.0

      # Load or Pull LocalStack Docker image
      - name: Get LocalStack Docker Image
        run: |
          if [ -f /tmp/localstack-cache/localstack.tar ]; then
            echo "Loading LocalStack Docker image from cache..."
            docker load -i /tmp/localstack-cache/localstack.tar
          else
            echo "LocalStack image not found in cache, pulling from Docker Hub..."
            docker pull localstack/localstack:3.7.0
            echo "Saving LocalStack image to cache..."
            mkdir -p /tmp/localstack-cache
            docker save localstack/localstack:3.7.0 -o /tmp/localstack-cache/localstack.tar
          fi

      # Cache Ryuk image
      - name: Cache Ryuk-0.7.0 image
        id: cache-ryuk
        uses: actions/cache@v3
        with:
          path: /tmp/ryuk-cache
          key: ${{ runner.os }}-ryuk-0.7.0

      # Load or Pull Ryuk Docker image
      - name: Get Ryuk Docker Image
        run: |
          if [ -f /tmp/ryuk-cache/ryuk.tar ]; then
            echo "Loading Ryuk Docker image from cache..."
            docker load -i /tmp/ryuk-cache/ryuk.tar
          else
            echo "Ryuk image not found in cache, pulling from Docker Hub..."
            docker pull testcontainers/ryuk:0.7.0
            echo "Saving Ryuk image to cache..."
            mkdir -p /tmp/ryuk-cache
            docker save testcontainers/ryuk:0.7.0 -o /tmp/ryuk-cache/ryuk.tar
          fi

      - name: Start LocalStack container
        run: |
          echo "Starting LocalStack container..."
          docker run -d --name localstack \
            -p 127.0.0.1:4566:4566 \
            -e SERVICES=dynamodb \
            localstack/localstack:3.7.0

      - name: Build and run tests
        run: mvn verify
