name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Phase 1: Basic Build and Unit Tests
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK and Cache Maven Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: maven

      - name: Compile and Run Unit Tests
        run: |
          mvn clean test package --batch-mode

      - name: Upload Packaged Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bank-account-recipients
          path: target/

  # Phase 2: Setup Docker Images and Run Integration Tests
  integration-tests:
    runs-on: ubuntu-latest
    needs: build-and-test  # Only run if the basic build and tests are successful
    timeout-minutes: 20
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK and Cache Maven Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: maven

      - name: Download Packaged Artifact
        uses: actions/download-artifact@v3
        with:
          name: bank-account-recipients
          path: target/

      - name: Setup Docker Images
        run: |
          docker pull localstack/localstack:3.7.0
          docker pull redis:6.2.6

      - name: Start LocalStack for Integration Tests
        run: |
          docker run -d --name localstack \
            -p 127.0.0.1:4566:4566 \
            -e SERVICES=dynamodb,ssm \
            localstack/localstack:3.7.0

      - name: Start Redis for Integration Tests
        run: |
          docker run -d --name redis -p 6379:6379 redis:6.2.6

      - name: Run Integration Tests with JaCoCo
        run: |
          mvn failsafe:integration-test jacoco:report --batch-mode

  # Phase 3: SonarCloud Analysis
  sonarcloud-analysis:
    runs-on: ubuntu-latest
    needs: integration-tests  # Only run if integration tests are successful
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK and Cache Maven Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: maven

      - name: Download Packaged Artifact
        uses: actions/download-artifact@v3
        with:
          name: bank-account-recipients
          path: target/

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
            mvn sonar:sonar \
              -Dsonar.projectKey=jcondotta_bank-account-recipients \
              -Dsonar.organization=jcondotta \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
