name: Linux 2023 Lambda Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LINUX_2023_LAMBDA_FUNCTION_NAME: "bank-account-recipients-java-17-graalvm"
      AWS_REGION: "eu-west-3"
      ARTIFACT_NAME: "function.zip"
      GRAALVM_VERSION: "17"
      GRAALVM_ARCH: "aarch64"  # Ensure the correct architecture if required

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM JDK with Maven cache
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '17'
          cache: maven

      # Build the GraalVM native image and package it as a ZIP for AWS Lambda
      - name: Build Native Image and Package as Zip
        run: |
          ./mvnw package -Dpackaging=docker-native

      # Verify the zip file is created
      - name: List the target directory
        run: |
          ls -al target