name: Microservice CI with LocalStack Docker Cache and Integration Tests

on:
  push:
    branches:
      - main

jobs:
  localstack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK with Maven cache
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven  # Automatically caches Maven dependencies

      # Cache Docker images (LocalStack + Testcontainers)
      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-docker
          run: echo "Checking for cached Docker images..."

      # Load LocalStack Docker image from cache if it exists
      - name: Load LocalStack Docker image from cache
        if: steps.cache-localstack.outputs.cache-hit == 'true'
        run: |
          echo "Loading cached LocalStack Docker image..."
          docker load -i /tmp/localstack-cache/localstack.tar

      # Pull necessary Docker images if not cached
      - name: Pre-pull Docker images for Testcontainers
        run: |
          echo "Pulling Testcontainers and LocalStack Docker images..."
          docker pull testcontainers/ryuk:0.7.0
          docker pull localstack/localstack:3.7.0

      - name: Save LocalStack Docker image to cache
        run: |
          echo "Saving LocalStack Docker image to cache..."
          mkdir -p /tmp/localstack-cache
          docker save localstack/localstack:3.7.0 -o /tmp/localstack-cache/localstack.tar

      - name: Start LocalStack manually
        run: |
          echo "Starting LocalStack container..."
          docker run -d --name localstack \
            -p 127.0.0.1:4566:4566 \
            -e SERVICES=dynamodb \
            localstack/localstack:3.7.0

      - name: Build and run (unit + integration) tests xD
        run: |
          mvn verify
