name: Microservice CI with LocalStack and Docker Cache

on:
  push:
    branches:
      - main

jobs:
  localstack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK with Maven cache
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven  # Automatically caches Maven dependencies

      # Cache LocalStack image
      - name: Cache LocalStack-3.7.0 image
        id: cache-localstack
        uses: actions/cache@v3
        with:
          path: /tmp/localstack-cache
          key: ${{ runner.os }}-localstack-3.7.0

      # Load LocalStack image from cache
      - name: Load LocalStack Docker image from cache
        if: steps.cache-localstack.outputs.cache-hit == 'true'
        run: docker load -i /tmp/localstack-cache/localstack.tar

      # Pull and save LocalStack image if not cached
      - name: Log and Pull LocalStack Docker image if not cached
        if: steps.cache-localstack.outputs.cache-hit != 'true'
        run: |
          echo "LocalStack image not found in cache, pulling from Docker Hub..."
          docker pull localstack/localstack:3.7.0
          
          echo "Saving LocalStack image to cache..."
          mkdir -p /tmp/localstack-cache
          docker save localstack/localstack:3.7.0 -o /tmp/localstack-cache/localstack.tar

      # Cache Ryuk(for testcontainers) image
      - name: Cache ryuk-0.7.0 image
        id: cache-ryuk
        uses: actions/cache@v3
        with:
          path: /tmp/ryuk-cache
          key: ${{ runner.os }}-ryuk-0.7.0

      # Load Ryuk image from cache
      - name: Load Ryuk Docker image from cache
        if: steps.cache-ryuk.outputs.cache-hit == 'true'
        run: docker load -i /tmp/ryuk-cache/ryuk.tar

      # Pull and save Ryuk image if not cached
      - name: Log and Pull Ryuk Docker image if not cached
        if: steps.cache-ryuk.outputs.cache-hit != 'true'
        run: |
          echo "Ryuk image not found in cache, pulling from Docker Hub..."
          docker pull testcontainers/ryuk:0.7.0
          
          echo "Saving Ryuk image to cache..."
          mkdir -p /tmp/ryuk-cache
          docker save testcontainers/ryuk:0.7.0 -o /tmp/ryuk-cache/ryuk.tar

      # Start LocalStack manually
      - name: Start LocalStack container
        run: |
          echo "Starting LocalStack container..."
          docker run -d --name localstack \
            -p 127.0.0.1:4566:4566 \
            -e SERVICES=dynamodb \
            localstack/localstack:3.7.0

      # Build and run unit + integration tests
      - name: Build and run tests
        run: mvn verify
