name: Microservice CI with Docker Cache and Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:3.7.0
        ports:
          - 127.0.0.1:4566:4566
          - 127.0.0.1:4510-4513:4510-4513
        env:
          SERVICES: dynamodb

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-localstack-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-localstack

      # Check if the cache was restored
      - name: Check if Docker cache exists
        run: |
          if [ -f /tmp/.docker-cache ]; then
            echo "Docker cache found!"
          else
            echo "Docker cache NOT found!"
          fi

      - name: Load Docker image from cache
        run: |
          if [ -f /tmp/.docker-cache ]; then
            docker load -i /tmp/.docker-cache || true
          fi

      # Optionally pull LocalStack image if not cached
      - name: Pull LocalStack image (if not cached)
        run: |
          if [ "$(docker images -q localstack/localstack:3.7.0 2> /dev/null)" == "" ]; then
            echo "Pulling LocalStack image"
            docker pull localstack/localstack:3.7.0
          else
            echo "LocalStack image found in cache"
          fi

      - name: Save Docker image to cache
        run: docker save -o /tmp/.docker-cache localstack/localstack:3.7.0

      - name: Build and run unit/integration tests
        run: mvn clean verify

      - name: Print LocalStack logs on failure
        if: failure()
        run: |
          docker logs $(docker ps -q --filter ancestor=localstack/localstack:3.7.0) || echo "No logs available for LocalStack."
