name: Microservice CI with LocalStack Docker Cache and Integration Tests

on:
  push:
    branches:
      - main

jobs:
  localstack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Cache LocalStack image
        id: cache-localstack
        uses: actions/cache@v3
        with:
          path: /tmp/localstack-cache
          key: localstack-${{ runner.os }}-3.7.0

      - name: Load LocalStack Docker image from cache
        if: steps.cache-localstack.outputs.cache-hit == 'true'
        run: docker load -i /tmp/localstack-cache/localstack.tar

      - name: Log and Pull LocalStack Docker image if not cached
        if: steps.cache-localstack.outputs.cache-hit != 'true'
        run: |
          echo "LocalStack image not found in cache, pulling from Docker Hub..."
          docker pull localstack/localstack:3.7.0
          
          echo "Saving LocalStack image to cache..."
          mkdir -p /tmp/localstack-cache
          docker save localstack/localstack:3.7.0 -o /tmp/localstack-cache/localstack.tar

      - name: Start LocalStack manually
        run: |
          docker run -d --name localstack \
            -p 127.0.0.1:4566:4566 \
            -p 127.0.0.1:4510-4513:4510-4513 \
            -e SERVICES=dynamodb \
            localstack/localstack:3.7.0
          echo "Waiting for LocalStack to be fully ready..."
          until curl -s http://localhost:4566/health | grep "\"dynamodb\": \"running\""; do
            echo "Waiting for LocalStack..."
            sleep 5
          done

      - name: Build and run unit tests
        run: mvn clean test

      - name: Run integration tests (skip unit tests)
        run: mvn verify -DskipTests=true -DskipITs=false

      - name: Print LocalStack logs on failure
        if: failure()
        run: docker logs $(docker ps -q --filter ancestor=localstack/localstack:3.7.0)
