name: Microservice CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-package:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK and Cache Maven Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: maven

      - name: Build and Package the Java Application
        run: mvn clean package --batch-mode

      - name: Upload Packaged Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bank-account-recipients
          path: target/bank-account-recipients-0.1.jar

  integration-tests:
    runs-on: ubuntu-latest
    needs: build-package
    timeout-minutes: 25

    env:
      LOCALSTACK_VERSION: "3.7.0"

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK and Cache Maven Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: maven

      - name: Start LocalStack Services for Integration Tests
        run: |
          echo "Starting LocalStack container..."
          docker run -d --name localstack \
            -p 127.0.0.1:4566:4566 \
            -e SERVICES=dynamodb \
            localstack/localstack:${{ env.LOCALSTACK_VERSION }}

      - name: Run Integration Tests with Failsafe Plugin
        run: mvn failsafe:integration-test --batch-mode

  docker-image-push:
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Download Packaged Artifact
        uses: actions/download-artifact@v3
        with:
          name: bank-account-recipients

      - name: Build Docker Image from Packaged Artifact
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/bank-account-recipients:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bank-account-recipients:latest

  aws-lambda-deploy:
    runs-on: ubuntu-latest
    needs: docker-image-push

    steps:
      - name: Configure AWS Credentials for Deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Deploy Packaged Artifact to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name bank-account-recipients-java-17 \
            --zip-file fileb://target/bank-account-recipients-0.1.jar