name: Microservice CI with LocalStack Docker Cache and Integration Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache JDK
        uses: actions/cache@v3
        with:
          path: ~/.sdkman/candidates/java
          key: ${{ runner.os }}-jdk-corretto-17
          restore-keys: |
            ${{ runner.os }}-jdk-corretto

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Cache LocalStack image
        id: cache-localstack
        uses: actions/cache@v3
        with:
          path: /tmp/localstack-cache
          key: ${{ runner.os }}-localstack-3.7.0

      - name: Load LocalStack Docker image from cache
        if: steps.cache-localstack.outputs.cache-hit == 'true'
        run: docker load -i /tmp/localstack-cache/localstack.tar

      - name: Log and Pull LocalStack Docker image if not cached
        if: steps.cache-localstack.outputs.cache-hit != 'true'
        run: |
          echo "LocalStack image not found in cache, pulling from Docker Hub..."
          docker pull localstack/localstack:3.7.0
          
          echo "Saving LocalStack image to cache..."
          mkdir -p /tmp/localstack-cache
          docker save localstack/localstack:3.7.0 -o /tmp/localstack-cache/localstack.tar

      - name: Start LocalStack manually
        run: |
          docker run -d --name localstack \
            -p 127.0.0.1:4566:4566 \
            -p 127.0.0.1:4510-4513:4510-4513 \
            -e SERVICES=dynamodb \
            localstack/localstack:3.7.0
          
          echo "Waiting for LocalStack to be fully ready..."
          
          MAX_ATTEMPTS=30  # Maximum number of attempts to check the service health
          SLEEP_TIME=10    # Wait time between attempts
          
          for i in $(seq 1 $MAX_ATTEMPTS); do
            echo "Checking LocalStack health... attempt #$i"
            HEALTH_STATUS=$(curl -s http://localhost:4566/health | jq -r .services.dynamodb)
            if [ "$HEALTH_STATUS" == "running" ]; then
              echo "LocalStack DynamoDB is running!"
              break
            fi
            echo "LocalStack not ready yet. Sleeping for $SLEEP_TIME seconds..."
            sleep $SLEEP_TIME
          done
          
          if [ "$HEALTH_STATUS" != "running" ]; then
            echo "LocalStack failed to start after $MAX_ATTEMPTS attempts."
            echo "Printing LocalStack logs for debugging:"
            docker logs localstack
            exit 1
          fi

      - name: Build and run unit tests
        run: mvn clean test
