name: Microservice CI with LocalStack and Docker Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-package:
    uses: ./.github/workflows/build-package.yml

#  integration-tests:
#    uses: ./.github/workflows/integration-tests.yml

#  docker:
#    needs: build
#    uses: ./.github/workflows/docker-build-and-push.yml
#    secrets:
#      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
#      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#  deploy:
#    needs: docker
#    uses: ./.github/workflows/lambda-deploy.yml
