name: Microservice CI with Docker Cache and Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-localstack-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-localstack

      - name: Load Docker image from cache
        run: |
          if [ -f /tmp/.docker-cache ]; then
            docker load -i /tmp/.docker-cache || true
          else
            echo "Docker image cache not found, proceeding with fresh pull."
          fi

      - name: Verify Docker image load
        run: docker images | grep localstack || echo "LocalStack image not loaded"

      - name: Pull LocalStack image (if not cached)
        run: docker pull localstack/localstack:3.7.0

      - name: Save Docker image to cache
        run: docker save -o /tmp/.docker-cache localstack/localstack:3.7.0

      - name: Start LocalStack manually
        run: |
          docker run -d --name localstack \
            -p 4566:4566 \
            -p 4510-4513:4510-4513 \
            -e SERVICES=dynamodb \
            localstack/localstack:3.7.0

      - name: Build and run unit tests
        run: mvn clean test

      - name: Run integration tests
        run: mvn verify -DskipTests=false -DskipITs=false

      - name: Print LocalStack logs on failure
        if: failure()
        run: docker logs $(docker ps -q --filter ancestor=localstack/localstack:3.7.0)
