name: Microservice CI with LocalStack and Docker Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # Phase 1: build and package
  build-package:
    uses: ./.github/workflows/build-and-package.yml

  # Phase 2: run integration tests
  integration-tests:
    needs: build-package
    uses: ./.github/workflows/integration-tests.yml

  # Phase 3: Docker Build and Push
  docker-build-push:
    needs: integration-tests
    uses: ./.github/workflows/docker-build-and-push.yml

#  integration-tests:
#    uses: ./.github/workflows/integration-tests.yml

#  docker:
#    needs: build
#    uses: ./.github/workflows/docker-build-and-push.yml
#    secrets:
#      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
#      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#  deploy:
#    needs: docker
#    uses: ./.github/workflows/lambda-deploy.yml
