name: Microservice CI with Docker Cache and Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:3.7.0
        ports:
          - 127.0.0.1:4566:4566
          - 127.0.0.1:4510-4513:4510-4513
        env:
          SERVICES: dynamodb

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Cache Docker layers from previous runs
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-localstack-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-localstack

      # Load Docker image from cache if it exists
      - name: Load Docker image from cache
        run: |
          if [ -f /tmp/.docker-cache ]; then
            docker load -i /tmp/.docker-cache || true
          else
            echo "Docker image cache not found, proceeding with fresh pull."
          fi

      # Pull the LocalStack image if it wasn't found in the cache
      - name: Pull LocalStack image (if not cached)
        run: docker pull localstack/localstack:3.7.0

      # Save the Docker image to cache after pulling
      - name: Save Docker image to cache
        run: docker save -o /tmp/.docker-cache localstack/localstack:3.7.0

      # Build and run unit tests
      - name: Build and run unit tests
        run: mvn clean test

      # Run integration tests
      - name: Run integration tests
        run: mvn verify -DskipTests=false -DskipITs=false

      # Print LocalStack logs in case of test failures
      - name: Print LocalStack logs on failure
        if: failure()
        run: docker logs $(docker ps -q --filter ancestor=localstack/localstack:3.7.0)
